remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Sno"
description: "A productivity ski app to check mountain weather and log personal stats."
author: 
  name: "Adrian Anaya"

theme: jekyll-theme-modernist